apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: quay.io/vathsalashetty96/argocd
  newName: quay.io/vathsalashetty96/argocd
  newTag: latest
resources:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis
