apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/vathsalashetty96/argo-cd//manifests/cluster-install?ref=stable

patchesStrategicMerge:
- argocd-known-hosts-mounts.yaml

resources:
- argocd-known-hosts.yaml
